parameters:
  - name: DisplayName
    type: string
    default: ''
  - name: ProjectPath
    type: string
  - name: ArtifactContainerName
    type: string
    default: 'Release'

jobs:
  - job: Migration
    displayName: '${{ parameters.DisplayName }}'
    pool:
      vmImage: 'ubuntu-latest'
    steps:

      - task: DotNetCoreCLI@2
        displayName: New Manifest for tool
        inputs:
          command: custom
          custom: 'new '
          arguments: tool-manifest

      - task: DotNetCoreCLI@2
        displayName: Install EF Tool
        inputs:
          command: custom
          custom: 'tool '
          arguments: install dotnet-ef

      - task: DotNetCoreCLI@2
        displayName: Create SQL Scripts
        inputs:
          command: custom
          custom: 'ef '
          arguments: migrations script --idempotent --output $(Build.ArtifactStagingDirectory)/${{ parameters.ArtifactContainerName }}_$(Build.BuildNumber)/migration.sql --project ${{ parameters.ProjectPath }} -- "none"
      
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: SQLScripts'
        inputs:
          PathtoPublish: $(Build.ArtifactStagingDirectory)/${{ parameters.ArtifactContainerName }}_$(Build.BuildNumber)/migration.sql
          ArtifactName: SQLScripts